baseURL = 'https://training.cycling-team.com/'

title = 'Cycling Team blog'

# Theme config
theme = 'hugo-book'
enableGitInfo = true

# Language config
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false

[caches]
[caches.images]
dir = ':cacheDir/images'

[params]
BookTheme = 'auto'


[languages]
[languages.de]
disabled = false
languageCode = 'de-DE'
languageDirection = 'ltr'
languageName = 'Deutsch'
title = 'Cycling Team Training'
weight = 1
[languages.de.params]
subtitle = 'Referenz, Tutorials und Erkl√§rungen'
[languages.en]
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = 'Cycling Team Training'
weight = 2

[menu]
[[menu.home]]
name = 'Home'
pageRef = '/'
weight = 1

[[menu.after]]
name = 'Github'
url = 'https://github.com/alex-shpak/hugo-book/'
weight = 10

[[menu.after]]
name = 'Hugo Themes'
url = 'https://themes.gohugo.io/themes/hugo-book/'
weight = 20
